header:
    frame_id: "left_tool"
pose:
    position:
        x: -0.0824041
        y: -0.0177783
        z: 0.0356282
    orientation:
        x: 0.577606
        y: -0.0992202
        z: -0.346624
        w: 0.732378
