header:
    frame_id: "left_tool"
pose:
    position:
        x: -0.0434094
        y: -0.0118873
        z: 0.0788188
    orientation:
        x: -0.0506069
        y: -0.417945
        z: 0.883689
        w: 0.204585
