header:
    frame_id: "left_tool"
pose:
    position:
        x: 0.0647054
        y: -0.184702
        z: 0.0486053
    orientation:
        x: -0.776835
        y: 0.0198125
        z: -0.371127
        w: 0.508329
