header:
    frame_id: "left_tool"
pose:
    position:
        x: 0.0894626
        y: -0.0171903
        z: -0.0091202
    orientation:
        x: 0.70767
        y: -0.250032
        z: 0.566648
        w: 0.339996
