header:
    frame_id: "left_tool"
pose:
    position:
        x: 0.0669236
        y: -0.0173101
        z: -0.0592469
    orientation:
        x: 0.859529
        y: 0.110042
        z: 0.271061
        w: 0.419078
