header:
    frame_id: "left_tool"
pose:
    position:
        x: -0.0283161
        y: -0.0196996
        z: -0.0851777
    orientation:
        x: -0.310748
        y: 0.820192
        z: -0.363586
        w: -0.31389
