header:
    frame_id: "left_tool"
pose:
    position:
        x: 0.00282217
        y: -0.018539
        z: -0.088934
    orientation:
        x: 0.0447626
        y: 0.89344
        z: -0.445451
        w: -0.0365452
