header:
    frame_id: "left_tool"
pose:
    position:
        x: -0.0494153
        y: -0.0716022
        z: -0.0319449
    orientation:
        x: 0.574828
        y: -0.407472
        z: 0.43755
        w: 0.558649
