header:
    frame_id: "left_tool"
pose:
    position:
        x: 0.0943054
        y: -0.00539517
        z: -0.00260059
    orientation:
        x: 0.620771
        y: 0.0958839
        z: 0.750542
        w: 0.20527
