header:
    frame_id: "left_tool"
pose:
    position:
        x: -0.0123723
        y: -0.0128391
        z: -0.0897151
    orientation:
        x: 0.78141
        y: -0.50614
        z: -0.210766
        w: -0.297989
