header:
    frame_id: "left_tool"
pose:
    position:
        x: 0.0726182
        y: -0.0196566
        z: -0.0552256
    orientation:
        x: 0.568229
        y: 0.627953
        z: -0.169495
        w: 0.504046
