header:
    frame_id: "left_tool"
pose:
    position:
        x: -0.0796189
        y: -0.0208159
        z: 0.0405232
    orientation:
        x: -0.550344
        y: 0.601113
        z: 0.156384
        w: 0.557969
